// Package snapshot records where block's vendored registry came from and
// proves that it still is what was vendored.
//
// registry/*.toml is a copy of block-registry at one revision, not a place
// recipes are written. Nothing in block can tell a hand edit from a synced
// one by looking at a recipe, so the provenance is written beside them in
// registry/SNAPSHOT and the recipes are hashed into it. `make registry-sync`
// writes that file; `make registry-verify` recomputes the hash and fails when
// the two disagree, which is what stops a recipe being fixed in the wrong
// repository.
//
// The digest is deliberately dull: a checksum manifest of the recipe files,
// hashed. It depends on nothing but the file names and their bytes, so the
// same revision always produces the same value on any machine, in any
// checkout order, in any year.
package snapshot

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

// FileName is the snapshot's name inside the registry directory.
const FileName = "SNAPSHOT"

// digestPrefix labels the hash so the file says what the value is.
const digestPrefix = "sha256:"

// Snapshot is the provenance of the vendored recipes.
type Snapshot struct {
	// Source is the repository the recipes were taken from.
	Source string `toml:"source"`
	// Revision is the full commit SHA that was vendored. Full, not short:
	// this is the value a human uses to go and read what block ships.
	Revision string `toml:"revision"`
	// Recipes is how many *.toml files came across, so an empty or
	// half-copied sync is visible in the file itself.
	Recipes int `toml:"recipes"`
	// Digest is Digest() over those files.
	Digest string `toml:"digest"`
}

// Parse reads a SNAPSHOT file. Every field is required: a snapshot missing
// one cannot answer the question it exists to answer.
func Parse(data []byte) (Snapshot, error) {
	var s Snapshot
	md, err := toml.Decode(string(data), &s)
	if err != nil {
		return Snapshot{}, fmt.Errorf("%s: %w", FileName, err)
	}
	if undecoded := md.Undecoded(); len(undecoded) > 0 {
		return Snapshot{}, fmt.Errorf("%s: unknown key %q", FileName, undecoded[0].String())
	}
	switch {
	case s.Source == "":
		return Snapshot{}, fmt.Errorf("%s: source is required", FileName)
	case !isFullSHA(s.Revision):
		return Snapshot{}, fmt.Errorf("%s: revision %q is not a full commit SHA", FileName, s.Revision)
	case s.Recipes <= 0:
		return Snapshot{}, fmt.Errorf("%s: recipes is %d, want the number of vendored recipes", FileName, s.Recipes)
	case !strings.HasPrefix(s.Digest, digestPrefix) || len(s.Digest) != len(digestPrefix)+sha256.Size*2:
		return Snapshot{}, fmt.Errorf("%s: digest %q is not %s followed by 64 hex digits", FileName, s.Digest, digestPrefix)
	}
	return s, nil
}

// sha1Len is the length of a git commit SHA in hex.
const sha1Len = 40

func isFullSHA(s string) bool {
	if len(s) != sha1Len {
		return false
	}
	_, err := hex.DecodeString(s)
	return err == nil
}

// Format renders a snapshot, header comment included. The comment is the
// only place a reader of block's source finds out that the directory is
// generated, so it is part of the file rather than a README elsewhere.
func (s Snapshot) Format() []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by \"make registry-sync\". Do not edit.\n")
	b.WriteString("#\n")
	b.WriteString("# The recipes beside this file are a vendored copy of block-registry at\n")
	b.WriteString("# the revision below, not a place to write recipes. Change one there and\n")
	b.WriteString("# run \"make registry-sync\"; \"make registry-verify\" fails on any edit made\n")
	b.WriteString("# here, so that a fix cannot land in the copy and be lost at the next sync.\n")
	b.WriteString("#\n")
	b.WriteString("# digest is a sha256 over the recipe files: one \"<sha256>  <name>\" line per\n")
	b.WriteString("# *.toml, sorted by name, hashed. It depends on nothing but their names and\n")
	b.WriteString("# bytes, so the same revision always produces the same value.\n")
	fmt.Fprintf(&b, "source = %q\n", s.Source)
	fmt.Fprintf(&b, "revision = %q\n", s.Revision)
	fmt.Fprintf(&b, "recipes = %d\n", s.Recipes)
	fmt.Fprintf(&b, "digest = %q\n", s.Digest)
	return b.Bytes()
}

// ErrNoRecipes reports a directory with nothing to vendor, which is a failed
// sync rather than an empty registry.
var ErrNoRecipes = errors.New("no recipes found")

// Digest hashes every *.toml in fsys and reports the digest and the count.
//
// The manifest it hashes is a text block of "<sha256 of the file>  <name>"
// lines sorted by name. Adding, removing or renaming a recipe changes it;
// changing a byte inside one changes it; the order the files happen to be
// read in does not.
func Digest(fsys fs.FS) (string, int, error) {
	entries, err := fs.ReadDir(fsys, ".")
	if err != nil {
		return "", 0, err
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".toml") {
			names = append(names, e.Name())
		}
	}
	if len(names) == 0 {
		return "", 0, ErrNoRecipes
	}
	sort.Strings(names)
	manifest := &bytes.Buffer{}
	for _, name := range names {
		data, err := fs.ReadFile(fsys, name)
		if err != nil {
			return "", 0, err
		}
		fmt.Fprintf(manifest, "%x  %s\n", sha256.Sum256(data), name)
	}
	sum := sha256.Sum256(manifest.Bytes())
	return digestPrefix + hex.EncodeToString(sum[:]), len(names), nil
}

// DriftError says which way the two disagree and what to do about it. The
// message is the whole point of the check: someone reading it has just
// edited a file they should not have.
type DriftError struct {
	Want, Got             Snapshot
	WantCount, GotCount   int
	WantDigest, GotDigest string
}

func (e *DriftError) Error() string {
	var b strings.Builder
	b.WriteString("registry/ does not match registry/SNAPSHOT.\n")
	if e.WantCount != e.GotCount {
		fmt.Fprintf(&b, "  recipes: %d recorded, %d present\n", e.WantCount, e.GotCount)
	}
	fmt.Fprintf(&b, "  digest:  %s recorded\n           %s present\n", e.WantDigest, e.GotDigest)
	b.WriteString("\nregistry/ is generated: it is a vendored copy of block-registry at " + e.Want.Revision[:shortSHA] + ".\n")
	b.WriteString("Make the change in " + e.Want.Source + ", then run \"make registry-sync\" here.\n")
	b.WriteString("To discard an accidental edit: git checkout -- registry/")
	return b.String()
}

// shortSHA is how much of a revision a message shows.
const shortSHA = 12

// Verify recomputes the digest of fsys and compares it with s.
func Verify(fsys fs.FS, s Snapshot) error {
	digest, count, err := Digest(fsys)
	if err != nil {
		return err
	}
	if digest == s.Digest && count == s.Recipes {
		return nil
	}
	return &DriftError{Want: s, WantCount: s.Recipes, GotCount: count, WantDigest: s.Digest, GotDigest: digest}
}
