package snapshot

import (
	"errors"
	"strings"
	"testing"
	"testing/fstest"
)

// recipes is a stand-in registry: two files whose contents are all the
// digest may depend on.
func recipes() fstest.MapFS {
	return fstest.MapFS{
		"foundry.toml": {Data: []byte("name = \"foundry\"\n")},
		"hermes.toml":  {Data: []byte("name = \"hermes\"\n")},
	}
}

func digestOf(t *testing.T, fsys fstest.MapFS) (string, int) {
	t.Helper()
	d, n, err := Digest(fsys)
	if err != nil {
		t.Fatal(err)
	}
	return d, n
}

func TestDigestDependsOnNamesAndBytesOnly(t *testing.T) {
	t.Parallel()
	want, count := digestOf(t, recipes())
	if count != 2 {
		t.Fatalf("Digest() counted %d recipes", count)
	}

	// The same files, whatever else is in the directory or how they are
	// spelled out: a snapshot must not change because a README was added.
	same := recipes()
	same["README.md"] = &fstest.MapFile{Data: []byte("docs")}
	same["SNAPSHOT"] = &fstest.MapFile{Data: []byte("revision = \"x\"\n")}
	same["sub"] = &fstest.MapFile{Mode: 0o755 | 1<<31}
	if got, _ := digestOf(t, same); got != want {
		t.Error("a non-recipe file changed the digest")
	}

	for _, tt := range []struct {
		name   string
		mutate func(fstest.MapFS)
	}{
		{"a byte inside a recipe", func(f fstest.MapFS) { f["foundry.toml"] = &fstest.MapFile{Data: []byte("name = \"Foundry\"\n")} }},
		{"a trailing newline", func(f fstest.MapFS) { f["foundry.toml"] = &fstest.MapFile{Data: []byte("name = \"foundry\"")} }},
		{"a recipe added", func(f fstest.MapFS) { f["reth.toml"] = &fstest.MapFile{Data: []byte("name = \"reth\"\n")} }},
		{"a recipe removed", func(f fstest.MapFS) { delete(f, "hermes.toml") }},
		// The manifest carries the name beside the hash, so moving content
		// between two files is a change even though the bytes are the same.
		{"a recipe renamed", func(f fstest.MapFS) {
			f["forge.toml"] = f["foundry.toml"]
			delete(f, "foundry.toml")
		}},
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			f := recipes()
			tt.mutate(f)
			if got, _ := digestOf(t, f); got == want {
				t.Errorf("%s did not change the digest", tt.name)
			}
		})
	}
}

func TestDigestIsStableAcrossRuns(t *testing.T) {
	t.Parallel()
	first, _ := digestOf(t, recipes())
	for range 5 {
		if got, _ := digestOf(t, recipes()); got != first {
			t.Fatalf("Digest() = %s then %s for the same files", first, got)
		}
	}
	if !strings.HasPrefix(first, "sha256:") || len(first) != len("sha256:")+64 {
		t.Errorf("Digest() = %q, want sha256: and 64 hex digits", first)
	}
}

func TestDigestNeedsRecipes(t *testing.T) {
	t.Parallel()
	if _, _, err := Digest(fstest.MapFS{"README.md": {Data: []byte("docs")}}); !errors.Is(err, ErrNoRecipes) {
		t.Errorf("Digest(no recipes) = %v, want ErrNoRecipes", err)
	}
}

const validSnapshot = `source = "https://github.com/nao1215/block-registry"
revision = "0123456789abcdef0123456789abcdef01234567"
recipes = 45
digest = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
`

func TestParse(t *testing.T) {
	t.Parallel()
	s, err := Parse([]byte(validSnapshot))
	if err != nil {
		t.Fatal(err)
	}
	if s.Recipes != 45 || s.Revision != "0123456789abcdef0123456789abcdef01234567" {
		t.Errorf("Parse() = %+v", s)
	}
	// A snapshot survives being written and read again, so "make
	// registry-sync" and "make registry-verify" cannot disagree about the
	// format.
	again, err := Parse(s.Format())
	if err != nil || again != s {
		t.Errorf("Parse(Format()) = %+v, %v", again, err)
	}
	if !strings.HasPrefix(string(s.Format()), "# Generated by") {
		t.Error("Format() must say the file is generated, first thing")
	}
}

func TestParseRejects(t *testing.T) {
	t.Parallel()
	for _, tt := range []struct{ name, body, want string }{
		{"garbage", "source = \n", "SNAPSHOT"},
		{"unknown key", validSnapshot + "vendored_at = \"2026-08-21\"\n", `unknown key "vendored_at"`},
		{"no source", strings.Replace(validSnapshot, `source = "https://github.com/nao1215/block-registry"`, "", 1), "source is required"},
		{"short revision", strings.Replace(validSnapshot, "0123456789abcdef0123456789abcdef01234567", "0123456", 1), "not a full commit SHA"},
		{"non-hex revision", strings.Replace(validSnapshot, "0123456789abcdef0123456789abcdef01234567", strings.Repeat("z", 40), 1), "not a full commit SHA"},
		{"no recipes", strings.Replace(validSnapshot, "recipes = 45", "recipes = 0", 1), "want the number of vendored recipes"},
		{"short digest", strings.Replace(validSnapshot, strings.Repeat("0", 64), "0000", 1), "64 hex digits"},
		{"unlabelled digest", strings.Replace(validSnapshot, "sha256:", "", 1), "64 hex digits"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			_, err := Parse([]byte(tt.body))
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Errorf("Parse() error = %v, want one containing %q", err, tt.want)
			}
		})
	}
}

func TestVerify(t *testing.T) {
	t.Parallel()
	f := recipes()
	digest, count := digestOf(t, f)
	s := Snapshot{
		Source:   "https://github.com/nao1215/block-registry",
		Revision: "0123456789abcdef0123456789abcdef01234567",
		Recipes:  count, Digest: digest,
	}
	if err := Verify(f, s); err != nil {
		t.Fatalf("Verify(unchanged) = %v", err)
	}

	// One character is enough, and the message has to say where the change
	// belongs — someone is reading it because they edited the wrong copy.
	edited := recipes()
	edited["foundry.toml"] = &fstest.MapFile{Data: []byte("name = \"foundry\" \n")}
	err := Verify(edited, s)
	if err == nil {
		t.Fatal("Verify(edited) = nil, want drift")
	}
	for _, want := range []string{"registry/ is generated", "block-registry", "make registry-sync", "git checkout -- registry/"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("drift message is missing %q:\n%s", want, err)
		}
	}

	// A miscounted snapshot is drift too, and says so in its own line.
	miscounted := s
	miscounted.Recipes = count + 1
	if err := Verify(f, miscounted); err == nil || !strings.Contains(err.Error(), "recipes:") {
		t.Errorf("Verify(miscounted) = %v", err)
	}
}
