// Package lockfile reads and writes block.lock: the facts block resolved from
// a block.toml. It records what was decided — exact version, executables,
// and the URL plus SHA-256 of every artifact per platform — and nothing about
// how to resolve, so installation needs only the block binary and this file.
package lockfile

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/BurntSushi/toml"

	"github.com/nao1215/block/internal/platform"
	"github.com/nao1215/block/internal/recipe"
	"github.com/nao1215/block/internal/version"
)

// FileName is the lockfile name.
const FileName = "block.lock"

// FormatVersion is the lockfile schema version this build writes.
const FormatVersion = 1

const header = "# This file is generated by block. Do not edit it by hand.\n"

// Lock is a parsed block.lock.
type Lock struct {
	Version int `toml:"version"`
	// Tools are sorted by name.
	Tools []Tool `toml:"tools"`
}

// Tool pins one tool.
type Tool struct {
	Name       string `toml:"name"`
	Constraint string `toml:"constraint"`
	Version    string `toml:"version"`
	// Bin lists the executables inside the artifact that `block exec` exposes.
	Bin []string `toml:"bin"`
	// StripComponents is how many leading path components to drop when
	// extracting the artifact.
	StripComponents int `toml:"strip_components,omitempty"`
	// Source fingerprints a project-local recipe (see recipe.Source.Hash) so
	// that editing it makes the pin stale. Empty for registry tools: a
	// registry change never invalidates an existing lock.
	Source string `toml:"source,omitempty"`
	// Artifacts are sorted by platform.
	Artifacts []Artifact `toml:"artifacts"`
}

// Artifact is the pinned download for one platform.
type Artifact struct {
	Platform string `toml:"platform"`
	URL      string `toml:"url"`
	SHA256   string `toml:"sha256"`
}

// Tool returns the entry with the given name.
func (l *Lock) Tool(name string) (*Tool, bool) {
	for i := range l.Tools {
		if l.Tools[i].Name == name {
			return &l.Tools[i], true
		}
	}
	return nil, false
}

// Artifact returns the tool's artifact for p.
func (t *Tool) Artifact(p platform.Platform) (Artifact, bool) {
	for _, a := range t.Artifacts {
		if a.Platform == p.String() {
			return a, true
		}
	}
	return Artifact{}, false
}

// SetArtifact adds or replaces the artifact for a.Platform keeping order.
func (t *Tool) SetArtifact(a Artifact) {
	for i := range t.Artifacts {
		if t.Artifacts[i].Platform == a.Platform {
			t.Artifacts[i] = a
			return
		}
	}
	t.Artifacts = append(t.Artifacts, a)
	sort.Slice(t.Artifacts, func(i, j int) bool { return t.Artifacts[i].Platform < t.Artifacts[j].Platform })
}

// ParsedVersion parses the pinned version.
func (t *Tool) ParsedVersion() (version.Version, error) {
	return version.Parse(t.Version)
}

// Sort orders tools by name and their artifacts by platform, in place.
func (l *Lock) Sort() {
	sort.Slice(l.Tools, func(i, j int) bool { return l.Tools[i].Name < l.Tools[j].Name })
	for i := range l.Tools {
		t := &l.Tools[i]
		sort.Slice(t.Artifacts, func(a, b int) bool { return t.Artifacts[a].Platform < t.Artifacts[b].Platform })
	}
}

// Load reads the lockfile at path.
func Load(path string) (*Lock, error) {
	data, err := os.ReadFile(path) //nolint:gosec // the path is the project's own block.lock
	if err != nil {
		return nil, err
	}
	l, err := Parse(data)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", filepath.Base(path), err)
	}
	return l, nil
}

// Parse parses lockfile bytes and validates every entry.
func Parse(data []byte) (*Lock, error) {
	var l Lock
	md, err := toml.Decode(string(data), &l)
	if err != nil {
		return nil, err
	}
	if undecoded := md.Undecoded(); len(undecoded) > 0 {
		return nil, fmt.Errorf("unknown key %q", undecoded[0].String())
	}
	if l.Version != FormatVersion {
		return nil, fmt.Errorf("unsupported lockfile version %d (this block writes version %d)", l.Version, FormatVersion)
	}
	seen := map[string]bool{}
	for i := range l.Tools {
		t := &l.Tools[i]
		if err := validateTool(t); err != nil {
			return nil, err
		}
		if seen[t.Name] {
			return nil, fmt.Errorf("tool %q is locked twice", t.Name)
		}
		seen[t.Name] = true
	}
	l.Sort()
	return &l, nil
}

func validateTool(t *Tool) error {
	if err := recipe.ValidateName(t.Name); err != nil {
		return err
	}
	c, err := version.ParseConstraint(t.Constraint)
	if err != nil {
		return fmt.Errorf("tool %q: %w", t.Name, err)
	}
	v, err := version.Parse(t.Version)
	if err != nil {
		return fmt.Errorf("tool %q: %w", t.Name, err)
	}
	// The pin has to be a version the constraint beside it could have chosen.
	// A lockfile arrives through pull requests and hand edits, and "resolved
	// 1.7 to 9.9.9" is exactly the edit that would otherwise install
	// something block.toml never asked for.
	if !c.Matches(v) {
		return fmt.Errorf("tool %q: version %s does not satisfy the constraint %q it was resolved from", t.Name, v, t.Constraint)
	}
	if len(t.Bin) == 0 {
		return fmt.Errorf("tool %q: bin is empty", t.Name)
	}
	seenBin := map[string]bool{}
	commands := map[string]string{}
	for _, b := range t.Bin {
		if err := recipe.ValidateBin(b); err != nil {
			return fmt.Errorf("tool %q: %w", t.Name, err)
		}
		if seenBin[b] {
			return fmt.Errorf("tool %q: bin %q is listed twice", t.Name, b)
		}
		seenBin[b] = true
		// Two paths that end in the same command name mean the command is
		// ambiguous inside one tool: a shim resolves it through this list
		// while PATH resolves it by directory order, and the two can pick
		// different executables. The comparison ignores case, because on
		// Windows "foo" and "FOO" are one command — see [recipe.CommandKey].
		if first, ok := commands[recipe.CommandKey(b)]; ok {
			return fmt.Errorf("tool %q: bin %q and %q are both the command %q",
				t.Name, first, b, recipe.CommandName(b))
		}
		commands[recipe.CommandKey(b)] = b
	}
	if t.StripComponents < 0 {
		return fmt.Errorf("tool %q: strip_components must not be negative", t.Name)
	}
	seen := map[string]bool{}
	for _, a := range t.Artifacts {
		if _, err := platform.Parse(a.Platform); err != nil {
			return fmt.Errorf("tool %q: %w", t.Name, err)
		}
		if seen[a.Platform] {
			return fmt.Errorf("tool %q: platform %s is locked twice", t.Name, a.Platform)
		}
		seen[a.Platform] = true
		if a.URL == "" {
			return fmt.Errorf("tool %q (%s): url is empty", t.Name, a.Platform)
		}
		if !validSHA256(a.SHA256) {
			return fmt.Errorf("tool %q (%s): sha256 %q is not a 64-character hex digest", t.Name, a.Platform, a.SHA256)
		}
	}
	return nil
}

func validSHA256(s string) bool {
	const hexLen = 64
	if len(s) != hexLen {
		return false
	}
	for _, r := range s {
		if (r < '0' || r > '9') && (r < 'a' || r > 'f') {
			return false
		}
	}
	return true
}

// Marshal renders the lockfile deterministically.
func Marshal(l *Lock) ([]byte, error) {
	l.Version = FormatVersion
	l.Sort()
	var buf bytes.Buffer
	buf.WriteString(header)
	buf.WriteString("\n")
	enc := toml.NewEncoder(&buf)
	enc.Indent = ""
	if err := enc.Encode(l); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Write atomically replaces the lockfile at path.
func Write(path string, l *Lock) error {
	data, err := Marshal(l)
	if err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".block.lock.*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	const mode = 0o644
	if err := os.Chmod(tmpName, mode); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	return nil
}
