// Package doc renders the parts of block's documentation that are derived
// from the registry rather than written by hand. The recipes are the only
// place a tool's name, commands, platforms and description are recorded, so
// the published catalogue is generated from them and checked for drift; a
// second hand-maintained list would be wrong within a release.
package doc

import (
	"bytes"
	"fmt"
	"slices"
	"sort"
	"strings"

	"github.com/nao1215/block/internal/recipe"
	"github.com/nao1215/block/registry"
)

// ecosystemTitle gives each registry ecosystem name the spelling its own
// community uses. An ecosystem missing here is titled from its name, so a new
// blockchain system in the registry still renders — just less prettily.
var ecosystemTitle = map[string]string{ //nolint:gochecknoglobals // immutable table
	"aptos":     "Aptos",
	"avalanche": "Avalanche",
	"bitcoin":   "Bitcoin",
	"cardano":   "Cardano",
	"celestia":  "Celestia",
	"cosmos":    "Cosmos",
	"ethereum":  "Ethereum",
	"fabric":    "Hyperledger Fabric",
	"ibc":       "IBC",
	"icp":       "Internet Computer",
	"ipfs":      "IPFS",
	"near":      "NEAR",
	"solana":    "Solana",
	"starknet":  "Starknet",
	"stellar":   "Stellar",
	"zk":        "Zero-knowledge circuits",
	"zksync":    "ZKsync",
}

// osTitle spells an operating system the way a reader chooses one, not the
// way Go's GOOS does.
var osTitle = map[string]string{ //nolint:gochecknoglobals // immutable table
	"linux":   "Linux",
	"darwin":  "macOS",
	"windows": "Windows",
}

// archTitle does the same for the architecture.
var archTitle = map[string]string{ //nolint:gochecknoglobals // immutable table
	"amd64": "x86-64",
	"arm64": "arm64",
}

// Tools renders doc/tools.md: every tool the embedded registry can install,
// grouped by the blockchain system it serves.
func Tools() ([]byte, error) {
	reg, err := registry.Builtin()
	if err != nil {
		return nil, err
	}
	snap, err := registry.Snapshot()
	if err != nil {
		return nil, err
	}

	ecosystems := reg.Ecosystems()
	var buf bytes.Buffer
	fmt.Fprintf(&buf, `# Tools

Every CLI block can install today: %d tools across %d blockchain systems, from
the registry snapshot embedded in the binary. The same list, offline, from the
block you have installed:

`+"```shell"+`
block list                 # every tool, with the systems it serves
block list ethereum        # one system, with the commands each tool provides
`+"```"+`

A tool that serves more than one system is listed under each — an IBC relayer
belongs to both Cosmos and IBC work. Commands are what lands on your PATH after
`+"`block sync`"+`. Platforms are the upstream's decision, not block's: where a
project publishes no build, block says so rather than substituting something
else.

Listing is discovery, not selection. Nothing here is installed until you name
it in `+"`block.toml`"+`, which stays the one place that says what your
toolchain is.

## Find a system

| System | Tools |
|:--|:--|
`, len(reg.Recipes()), len(ecosystems))

	for _, eco := range ecosystems {
		recs := reg.ByEcosystem(eco)
		title := title(eco)
		fmt.Fprintf(&buf, "| [%s](#%s) | %d |\n", title, anchor(title), len(recs))
	}

	for _, eco := range ecosystems {
		fmt.Fprintf(&buf, "\n## %s\n\n", title(eco))
		fmt.Fprint(&buf, "| Tool | Commands | Platforms | What it is |\n|:--|:--|:--|:--|\n")
		for _, rec := range reg.ByEcosystem(eco) {
			fmt.Fprintf(&buf, "| `%s` | %s | %s | %s |\n",
				rec.Name, commands(rec), platforms(rec), rec.Description)
		}
	}

	fmt.Fprintf(&buf, `
## Not here yet?

A tool the registry does not carry — or one you want from a fork — is declared
in your own `+"`block.toml`"+`, with the same fields a registry recipe uses:

`+"```toml"+`
[tools.foo]
version = "1.2"

[tools.foo.source]
type = "github_release"
repo = "example/foo"
asset = "foo_{version}_{os}_{arch}.tar.gz"
bin = ["foo"]
`+"```"+`

See [Bring your own tool](/cookbook/#bring-your-own-tool) for the whole set of
knobs. Nobody waits for a registry merge; promoting a definition to
[block-registry](%s) afterwards is a copy.

<!-- Generated by "make doc" from the recipes in registry/, vendored from
     block-registry at %s. Do not edit by hand. -->
`, snap.Source, snap.Revision)

	return buf.Bytes(), nil
}

// title spells an ecosystem for a heading.
func title(eco string) string {
	if t, ok := ecosystemTitle[eco]; ok {
		return t
	}
	return eco
}

// anchor is the GitHub/Hugo heading anchor for a title.
func anchor(t string) string {
	return strings.ReplaceAll(strings.ToLower(t), " ", "-")
}

// commands lists the executables a tool puts on PATH, by the name they are
// run as rather than by their path inside the archive.
func commands(rec recipe.Recipe) string {
	names := make([]string, 0, len(rec.Source.Bin))
	for _, b := range rec.Source.Bin {
		name := b
		if i := strings.LastIndexAny(name, "/"); i >= 0 {
			name = name[i+1:]
		}
		name = strings.TrimSuffix(name, ".exe")
		names = append(names, "`"+name+"`")
	}
	return strings.Join(names, ", ")
}

// platforms renders the upstream's platform coverage compactly: one entry per
// operating system, with the architectures it ships for.
func platforms(rec recipe.Recipe) string {
	byOS := map[string][]string{}
	var order []string
	for _, p := range rec.Source.SupportedPlatforms() {
		if _, seen := byOS[p.OS]; !seen {
			order = append(order, p.OS)
		}
		byOS[p.OS] = append(byOS[p.OS], arch(p.Arch))
	}
	sort.Slice(order, func(i, j int) bool { return osRank(order[i]) < osRank(order[j]) })

	out := make([]string, 0, len(order))
	for _, os := range order {
		out = append(out, fmt.Sprintf("%s (%s)", osName(os), strings.Join(byOS[os], ", ")))
	}
	return strings.Join(out, ", ")
}

// osOrder keeps operating systems in a fixed reading order rather than the
// order a recipe happens to list its platforms in. An OS missing here sorts
// last, so a platform block does not know about still renders.
var osOrder = []string{"linux", "darwin", "windows"} //nolint:gochecknoglobals // immutable table

func osRank(os string) int {
	if i := slices.Index(osOrder, os); i >= 0 {
		return i
	}
	return len(osOrder)
}

func osName(os string) string {
	if t, ok := osTitle[os]; ok {
		return t
	}
	return os
}

func arch(a string) string {
	if t, ok := archTitle[a]; ok {
		return t
	}
	return a
}
